//! Phase 1 integration tests.
//!
//! - Step 1 (pass-through gateway): stubs a fake upstream with `wiremock`,
//!   points the gateway at it, and verifies request/response byte-equality.
//! - Step 2 (pairing): loads the committed Phase 0 fixture corpus, builds the
//!   `PairingIndex`, asserts the orphan invariant, and snapshots each index
//!   with `insta`. The Rust index must match the Python reference
//!   (`tests/phase0/pairing.py`) on the same fixtures.

use std::collections::BTreeMap;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use serde::Serialize;
use serde_json::{Value, json};
use trimwire::config::Config;
use trimwire::ledger::Ledger;
use trimwire::pairing::PairingIndex;
use trimwire::proxy::gateway;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

/// The committed synthetic fixtures, generated by
/// `tests/phase0/dump_fixtures.py`. Keep in sync with that script's list.
const FIXTURES: &[&str] = &[
    "parallel_tool_use",
    "long_session",
    "huge_tool_result",
    "compact_boundary",
    "screenshot_heavy",
    "failure_heavy",
];

/// Absolute path to `tests/fixtures/<name>.json`.
fn fixture_path(name: &str) -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures"]
        .iter()
        .collect::<PathBuf>()
        .join(format!("{name}.json"))
}

/// Raw bytes of the full fixture request body (the `/v1/messages` envelope).
fn load_fixture_bytes(name: &str) -> Vec<u8> {
    let path = fixture_path(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()))
}

/// Load `tests/fixtures/<name>.json` and return its `messages[]` array.
fn load_fixture_messages(name: &str) -> Vec<Value> {
    let raw = load_fixture_bytes(name);
    let body: Value =
        serde_json::from_slice(&raw).unwrap_or_else(|e| panic!("parse fixture {name}: {e}"));
    body["messages"]
        .as_array()
        .unwrap_or_else(|| panic!("fixture {name} has no messages[] array"))
        .clone()
}

/// The standard SlidingWindow config the Python invariant suite exercises
/// (denylist `Bash`, keep 4, no exempt). Matches `dump_expected.py`.
fn standard_sliding_cfg() -> trimwire::config::SlidingWindowConfig {
    trimwire::config::SlidingWindowConfig {
        enabled: true,
        keep_recent_turns: 4,
        denylist_tools: vec!["Bash".to_owned()],
        exempt_tools: vec![],
        stub: "[trimwire: elided, older than sliding window]".to_owned(),
    }
}

/// Deterministic, snapshot-friendly view of a `PairingIndex`. `BTreeMap`
/// sorts ids so snapshots don't depend on `HashMap` iteration order.
#[derive(Serialize)]
struct IndexView {
    uses: BTreeMap<String, [usize; 2]>,
    results: BTreeMap<String, [usize; 2]>,
}

impl IndexView {
    fn of(idx: &PairingIndex) -> Self {
        let collect = |m: &std::collections::HashMap<String, (usize, usize)>| {
            m.iter().map(|(k, &(a, b))| (k.clone(), [a, b])).collect()
        };
        IndexView {
            uses: collect(&idx.uses),
            results: collect(&idx.results),
        }
    }
}

/// Every fixture loads, builds an index, and passes the orphan invariant.
#[test]
fn fixtures_build_and_validate() {
    for name in FIXTURES {
        let messages = load_fixture_messages(name);
        let idx = PairingIndex::build(&messages);
        idx.validate()
            .unwrap_or_else(|e| panic!("fixture {name} failed validate: {e}"));
        // Every fixture in the corpus exercises at least one tool pair.
        assert!(
            !idx.uses.is_empty() && !idx.results.is_empty(),
            "fixture {name} should contain tool pairs"
        );
    }
}

/// Snapshot each fixture's pairing index so regressions in `build` are caught.
#[test]
fn fixtures_pairing_snapshot() {
    for name in FIXTURES {
        let messages = load_fixture_messages(name);
        let idx = PairingIndex::build(&messages);
        insta::assert_json_snapshot!(format!("pairing_{name}"), IndexView::of(&idx));
    }
}

/// Bind an OS-assigned free port and return the LIVE listener plus its address.
/// The listener is handed straight to `gateway::run_from_listener`, so the port
/// stays held continuously — no bind→drop→rebind window for a parallel test to
/// race into. The old `bind_free_port` dropped the listener before the gateway
/// re-bound the same addr, which let two concurrent tests grab the same port
/// under load (the intermittent integration-test flake).
async fn bind_listener() -> (tokio::net::TcpListener, SocketAddr) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("bind ephemeral port");
    let addr = listener.local_addr().expect("local_addr");
    (listener, addr)
}

/// Poll until the spawned gateway accepts connections (replaces a flaky fixed
/// sleep). Returns as soon as it's connectable, so the happy path stays fast; the
/// generous ceiling (≈6s) only matters under heavy CPU contention — when the whole
/// suite runs in parallel on a loaded box, the spawned gateway task can be slow to
/// get scheduled, and a tight budget would `panic!` on a gateway that was merely
/// late, not dead.
async fn await_listening(addr: SocketAddr) {
    for _ in 0..600 {
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return;
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    panic!("gateway never started listening on {addr} (6s budget)");
}

/// Poll the mock upstream until its request log shows at least `n` requests.
/// wiremock records a request slightly after the client gets its response, so a
/// single immediate read can race (and flake) under heavy parallel test load.
async fn await_received(server: &MockServer, n: usize) -> Vec<wiremock::Request> {
    for _ in 0..200 {
        let got = server.received_requests().await.expect("requests log");
        if got.len() >= n {
            return got;
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    server.received_requests().await.expect("requests log")
}

#[tokio::test]
async fn pass_through_byte_equality() {
    // 1. Fake upstream that captures the request and echoes a known body.
    let upstream = MockServer::start().await;
    let body_out = b"hello from upstream";
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "application/json")
                .set_body_bytes(body_out.to_vec()),
        )
        .mount(&upstream)
        .await;

    // 2. Launch the gateway against that upstream on an ephemeral port.
    //    Default config has all strategies off → pure pass-through.
    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(Config::default()),
            Ledger::disabled(),
            None,
        )
        .await;
    });

    // Tiny settle so the server starts accepting.
    await_listening(gw_addr).await;

    // 3. POST a known body through the gateway.
    let body_in = br#"{"model":"claude-sonnet-4-5","messages":[]}"#;
    let client = reqwest::Client::builder().build().expect("reqwest client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("authorization", "Bearer test-token")
        .header("anthropic-version", "2023-06-01")
        .body(body_in.to_vec())
        .send()
        .await
        .expect("send through gateway");

    assert_eq!(res.status().as_u16(), 200);
    let got = res.bytes().await.expect("response bytes");
    assert_eq!(
        got.as_ref(),
        body_out,
        "response body passes through verbatim"
    );

    // 4. Check upstream actually received the same request bytes.
    let received = await_received(&upstream, 1).await;
    assert_eq!(received.len(), 1, "exactly one upstream request");
    let req = &received[0];
    assert_eq!(req.method, wiremock::http::Method::POST);
    assert_eq!(req.body, body_in, "request body forwarded byte-for-byte");
    // Auth header forwarded intact.
    let auth = req
        .headers
        .get("authorization")
        .expect("authorization header forwarded")
        .to_str()
        .unwrap();
    assert_eq!(auth, "Bearer test-token");
}

/// An SSE (`text/event-stream`) response — the real Anthropic response shape —
/// streams back through the gateway byte-for-byte, with the content-type intact.
/// Exercises the `MeteredBody` SSE-scanning path (it parses `message_start` /
/// `message_delta` line events for token metering) on the live proxy path, not
/// just a plain JSON body.
#[tokio::test]
async fn sse_response_streams_back_verbatim() {
    let upstream = MockServer::start().await;
    // A representative multi-event SSE body (events are `\n\n`-separated).
    let sse: &[u8] = b"event: message_start\ndata: {\"type\":\"message_start\",\"message\":{\"usage\":{\"input_tokens\":10,\"output_tokens\":1}}}\n\nevent: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"delta\":{\"text\":\"hi\"}}\n\nevent: message_delta\ndata: {\"type\":\"message_delta\",\"usage\":{\"output_tokens\":2}}\n\nevent: message_stop\ndata: {\"type\":\"message_stop\"}\n\n";
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("content-type", "text/event-stream")
                .set_body_bytes(sse.to_vec()),
        )
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(Config::default()),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let body_in = br#"{"model":"claude-sonnet-4-5","messages":[]}"#;
    let client = reqwest::Client::builder().build().expect("reqwest client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("authorization", "Bearer test-token")
        .header("anthropic-version", "2023-06-01")
        .body(body_in.to_vec())
        .send()
        .await
        .expect("send through gateway");

    assert_eq!(res.status().as_u16(), 200);
    assert_eq!(
        res.headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok()),
        Some("text/event-stream"),
        "SSE content-type preserved through the gateway"
    );
    let got = res.bytes().await.expect("response bytes");
    assert_eq!(
        got.as_ref(),
        sse,
        "SSE stream is forwarded byte-for-byte (metering must not mutate it)"
    );
}

// ---------------------------------------------------------------------------
// Step 2/3: SlidingWindow strategy
// ---------------------------------------------------------------------------

/// Rust output must be byte-identical to the Python reference on every
/// fixture (canonical sorted-key compact JSON). Expected files are generated
/// by `tests/phase0/dump_expected.py`.
#[test]
fn sliding_window_matches_python_reference() {
    for name in FIXTURES {
        let mut messages = load_fixture_messages(name);
        trimwire::strategies::sliding_window::apply(&mut messages, &standard_sliding_cfg())
            .unwrap_or_else(|e| panic!("apply on {name}: {e}"));
        let got = serde_json::to_string(&messages).expect("serialize");

        let expected_path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "expected"]
            .iter()
            .collect::<PathBuf>()
            .join(format!("sliding_window__{name}.json"));
        let expected = std::fs::read_to_string(&expected_path)
            .unwrap_or_else(|e| panic!("read expected {}: {e}", expected_path.display()));

        assert_eq!(
            got,
            expected.trim_end(),
            "fixture {name}: Rust SlidingWindow output diverges from Python reference"
        );
    }
}

/// Regression snapshot of a stubbed fixture (errored Bash calls, old ones
/// elided). `failure_heavy` is small and exercises the stub path.
#[test]
fn sliding_window_snapshot() {
    let mut messages = load_fixture_messages("failure_heavy");
    trimwire::strategies::sliding_window::apply(&mut messages, &standard_sliding_cfg()).unwrap();
    insta::assert_json_snapshot!("sliding_window_failure_heavy", messages);
}

// ---------------------------------------------------------------------------
// Step 3: gateway actually prunes the forwarded body
// ---------------------------------------------------------------------------

const SW_STUB: &str = "[trimwire: elided, older than sliding window]";

/// Count tool_result blocks whose content equals the SlidingWindow stub.
fn count_stubbed(messages: &[Value]) -> usize {
    messages
        .iter()
        .filter_map(|m| m.get("content").and_then(Value::as_array))
        .flatten()
        .filter(|b| {
            b.get("content")
                .and_then(Value::as_str)
                .is_some_and(|s| s.starts_with(SW_STUB))
        })
        .count()
}

/// With SlidingWindow enabled, the body the upstream receives has old Bash
/// pairs stubbed, stays orphan-free, and is smaller than the original.
#[tokio::test]
async fn gateway_prunes_messages() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    let mut config = Config::default();
    config.strategies.sliding_window = standard_sliding_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let body_in = load_fixture_bytes("long_session");
    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .body(body_in.clone())
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    assert_eq!(received.len(), 1);
    let fwd = &received[0].body;

    // Body shrank (old inputs -> {}, old results -> stub).
    assert!(
        fwd.len() < body_in.len(),
        "forwarded body ({}) should be smaller than original ({})",
        fwd.len(),
        body_in.len()
    );

    let fwd_body: Value = serde_json::from_slice(fwd).expect("parse forwarded");
    let messages = fwd_body["messages"].as_array().expect("messages[]");
    // 100 turns, keep 4 -> 96 stubbed.
    assert_eq!(count_stubbed(messages), 96);
    // No orphans introduced.
    PairingIndex::build(messages)
        .validate()
        .expect("forwarded body orphan-free");
    // The system field is untouched.
    assert_eq!(fwd_body["system"], body_in_json(&body_in)["system"]);
}

/// When no strategy fires (denylist doesn't match the fixture's tools), the
/// gateway forwards the original bytes verbatim — preserving the cache prefix.
#[tokio::test]
async fn gateway_passes_through_when_nothing_fires() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    // screenshot_heavy uses only mcp__playwright__* tools; Bash denylist
    // matches nothing -> no mutation.
    let mut config = Config::default();
    config.strategies.sliding_window = standard_sliding_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let body_in = load_fixture_bytes("screenshot_heavy");
    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .body(body_in.clone())
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    assert_eq!(
        received[0].body, body_in,
        "no-op run must forward the body byte-for-byte"
    );
}

fn body_in_json(bytes: &[u8]) -> Value {
    serde_json::from_slice(bytes).expect("parse fixture body")
}

/// Even with strategies enabled, a non-/v1/messages POST is forwarded
/// verbatim (only /v1/messages is pruned).
#[tokio::test]
async fn gateway_passes_through_non_messages_post() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/other"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    let mut config = Config::default();
    config.strategies.sliding_window = standard_sliding_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    // A body that WOULD be pruned at /v1/messages.
    let body_in = load_fixture_bytes("long_session");
    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/other"))
        .header("content-type", "application/json")
        .body(body_in.clone())
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    assert_eq!(
        received[0].body, body_in,
        "non-/v1/messages POST must forward the body byte-for-byte"
    );
}

/// A GET is forwarded untouched (no body, no mutation) even with strategies on.
#[tokio::test]
async fn gateway_passes_through_get() {
    let upstream = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/v1/models"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"{\"models\":[]}".to_vec()))
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    let mut config = Config::default();
    config.strategies.sliding_window = standard_sliding_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .get(format!("http://{gw_addr}/v1/models"))
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    assert_eq!(received.len(), 1);
    assert_eq!(received[0].method, wiremock::http::Method::GET);
    assert!(received[0].body.is_empty(), "GET has no body");
}

// ---------------------------------------------------------------------------
// Step 4: ImageStrip strategy
// ---------------------------------------------------------------------------

/// Standard ImageStrip config matching dump_expected.py (exact screenshot
/// tool, keep 1).
fn standard_image_cfg() -> trimwire::config::ImageStripConfig {
    trimwire::config::ImageStripConfig {
        enabled: true,
        applies_to_tools: vec!["mcp__playwright__browser_take_screenshot".to_owned()],
        keep_recent_count: 1,
        stub: "[trimwire: image stripped]".to_owned(),
    }
}

/// Rust ImageStrip output must be byte-identical to the Python reference on
/// every fixture. Expected files via `tests/phase0/dump_expected.py`.
#[test]
fn image_strip_matches_python_reference() {
    for name in FIXTURES {
        let mut messages = load_fixture_messages(name);
        trimwire::strategies::image_strip::apply(&mut messages, &standard_image_cfg())
            .unwrap_or_else(|e| panic!("apply on {name}: {e}"));
        let got = serde_json::to_string(&messages).expect("serialize");

        let expected_path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "expected"]
            .iter()
            .collect::<PathBuf>()
            .join(format!("image_strip__{name}.json"));
        let expected = std::fs::read_to_string(&expected_path)
            .unwrap_or_else(|e| panic!("read expected {}: {e}", expected_path.display()));

        assert_eq!(
            got,
            expected.trim_end(),
            "fixture {name}: Rust ImageStrip output diverges from Python reference"
        );
    }
}

/// On the screenshot-heavy fixture, ImageStrip strips the 2 older images
/// (keep 1), shrinks the body, and leaves no orphans.
#[test]
fn image_strip_shrinks_screenshot_fixture() {
    let mut messages = load_fixture_messages("screenshot_heavy");
    let before = serde_json::to_vec(&messages).unwrap().len();
    let stub = "[trimwire: image stripped]";
    trimwire::strategies::image_strip::apply(&mut messages, &standard_image_cfg()).unwrap();
    let after = serde_json::to_vec(&messages).unwrap().len();

    assert!(after < before, "body should shrink ({after} < {before})");
    let stubbed = messages
        .iter()
        .filter_map(|m| m.get("content").and_then(Value::as_array))
        .flatten()
        .filter(|b| {
            b.get("content")
                .and_then(Value::as_str)
                .is_some_and(|s| s.starts_with(stub))
        })
        .count();
    assert_eq!(stubbed, 2, "3 screenshots, keep 1 -> 2 stripped");
    PairingIndex::build(&messages).validate().unwrap();
}

// ---------------------------------------------------------------------------
// Step 5: ledger records through the gateway (SPIKE §9 cache-prefix guard)
// ---------------------------------------------------------------------------

/// Poll the read-only ledger report until it has at least `n` rows.
async fn wait_for_rows(db_path: &str, n: u64) -> trimwire::ledger::Report {
    for _ in 0..40 {
        if let Ok(r) = trimwire::ledger::Ledger::report(db_path) {
            if r.total_requests >= n {
                return r;
            }
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    panic!("ledger did not reach {n} rows in time");
}

/// End-to-end: with SlidingWindow enabled, one firing request (long_session,
/// Bash) and one no-op request (screenshot_heavy, no Bash) both get recorded.
/// The no-op request must keep its prefix hash stable → stability ratio 1.0.
#[tokio::test]
async fn gateway_ledger_records_and_prefix_is_stable() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let dir = tempfile::tempdir().expect("tempdir");
    let db_path = dir.path().join("ledger.db").to_str().unwrap().to_owned();
    let ledger = Ledger::open(&db_path, 365);

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    let mut config = Config::default();
    config.strategies.sliding_window = standard_sliding_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(listener, upstream_uri, Arc::new(config), ledger, None)
            .await;
    });
    await_listening(gw_addr).await;

    let client = reqwest::Client::builder().build().expect("client");
    for fixture in ["long_session", "screenshot_heavy"] {
        let res = client
            .post(format!("http://{gw_addr}/v1/messages"))
            .header("content-type", "application/json")
            .body(load_fixture_bytes(fixture))
            .send()
            .await
            .expect("send");
        assert_eq!(res.status().as_u16(), 200);
    }

    let report = wait_for_rows(&db_path, 2).await;
    assert_eq!(report.total_requests, 2);
    // long_session fired SlidingWindow; screenshot_heavy was a no-op.
    assert_eq!(report.per_strategy, vec![("sliding_window".to_owned(), 1)]);
    assert_eq!(report.cache_stability.no_strategy_total, 1);
    assert_eq!(report.cache_stability.no_strategy_stable, 1);
    assert!((report.cache_stability.ratio - 1.0).abs() < 1e-9);
    assert!(
        report.bytes_saved() > 0,
        "pruning should net positive savings"
    );
}

/// With ImageStrip enabled, the gateway strips older screenshots from the
/// forwarded body (deferred Step 4 coverage: the full apply_to_body→gateway
/// path for ImageStrip).
#[tokio::test]
async fn gateway_strips_images() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    let mut config = Config::default();
    config.strategies.image_strip = standard_image_cfg();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let body_in = load_fixture_bytes("screenshot_heavy");
    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .body(body_in.clone())
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    let fwd = &received[0].body;
    assert!(
        fwd.len() < body_in.len(),
        "image-stripped body should shrink"
    );
    let fwd_body: Value = serde_json::from_slice(fwd).expect("parse forwarded");
    let messages = fwd_body["messages"].as_array().expect("messages[]");
    let stubbed = messages
        .iter()
        .filter_map(|m| m.get("content").and_then(Value::as_array))
        .flatten()
        .filter(|b| {
            b.get("content")
                .and_then(Value::as_str)
                .is_some_and(|s| s.starts_with("[trimwire: image stripped]"))
        })
        .count();
    assert_eq!(stubbed, 2, "3 screenshots, keep 1 -> 2 stripped");
    PairingIndex::build(messages)
        .validate()
        .expect("no orphans");
}

/// A gateway/upstream failure returns an Anthropic-shaped JSON error envelope
/// (not plain text), so Claude Code's SDK renders it cleanly (SPIKE §6).
#[tokio::test]
async fn gateway_error_is_anthropic_json() {
    // A closed port → upstream connection refused → 502.
    let dead = {
        let l = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let a = l.local_addr().unwrap();
        drop(l);
        a
    };
    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = format!("http://{dead}");
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(Config::default()),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .body("{\"messages\":[]}")
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 502);
    assert_eq!(
        res.headers()
            .get("content-type")
            .map(|v| v.to_str().unwrap()),
        Some("application/json")
    );
    let body: Value = res.json().await.expect("json error body");
    assert_eq!(body["type"], "error");
    assert_eq!(body["error"]["type"], "gateway_error");
}

/// The headline fix: a plain coding session (repeated file reads + a failed
/// Bash, NO browser tools, NO screenshots) is now pruned out of the box by the
/// default-on cross_turn_dedup + failed_input_purge — previously inert.
#[tokio::test]
async fn gateway_prunes_a_plain_coding_session() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    // Build a coding session: one old failed Bash, then 6 identical Reads.
    let mut messages = vec![
        json_msg("user", "fix the bug"),
        json!({"role": "assistant", "content": [
            {"type": "tool_use", "id": "u_bash", "name": "Bash",
             "input": {"command": "cargo test --some-very-long-flag-that-failed"}}
        ]}),
        json!({"role": "user", "content": [
            {"type": "tool_result", "tool_use_id": "u_bash", "is_error": true,
             "content": "error: no such flag"}
        ]}),
    ];
    let big = "x".repeat(4000); // a chunky file each read re-sends
    for i in 0..6 {
        let uid = format!("u_read{i}");
        messages.push(json_msg("user", "read it again"));
        messages.push(json!({"role": "assistant", "content": [
            {"type": "tool_use", "id": uid, "name": "Read", "input": {"path": "/src/lib.rs"}}
        ]}));
        messages.push(json!({"role": "user", "content": [
            {"type": "tool_result", "tool_use_id": uid, "content": big.clone()}
        ]}));
    }
    let body_in = serde_json::to_vec(&json!({"model": "claude", "messages": messages})).unwrap();

    // Default-style config: the two workhorse strategies on; no browser/image.
    let mut config = Config::default();
    config.strategies.cross_turn_dedup.enabled = true;
    config.strategies.failed_input_purge.enabled = true;

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(config),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .body(body_in.clone())
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    let received = await_received(&upstream, 1).await;
    let fwd = &received[0].body;
    assert!(
        fwd.len() < body_in.len() / 2,
        "coding session should shrink a lot: {} -> {}",
        body_in.len(),
        fwd.len()
    );
    let fwd_body: Value = serde_json::from_slice(fwd).unwrap();
    let messages = fwd_body["messages"].as_array().unwrap();
    // 5 of the 6 identical reads superseded; the failed Bash input cleared.
    let superseded = serde_json::to_string(messages)
        .unwrap()
        .matches("superseded by a later identical call")
        .count();
    assert_eq!(superseded, 5, "5 older identical reads deduped");
    // Shape-preserving purge: the small failed command is kept (the model still
    // sees what failed) — only bulk would be elided.
    assert_eq!(
        messages[1]["content"][0]["input"]["command"],
        json!("cargo test --some-very-long-flag-that-failed"),
        "failed Bash command kept"
    );
    PairingIndex::build(messages)
        .validate()
        .expect("no orphans");
}

/// Small helper for a plain text user/assistant message.
fn json_msg(role: &str, text: &str) -> Value {
    json!({"role": role, "content": [{"type": "text", "text": text}]})
}

/// The headline contract: the SSE response is **streamed**, not buffered. A
/// raw upstream sends one chunk, waits, sends another, then closes — so a
/// streaming proxy delivers the first chunk long before the second, while a
/// buffering one would deliver both at once. Guards against a future refactor
/// (or hyper bump) that silently starts buffering `text/event-stream`.
#[tokio::test]
async fn sse_response_streams_incrementally_not_buffered() {
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    const DELAY: Duration = Duration::from_millis(400);

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let up_addr = listener.local_addr().unwrap();
    tokio::spawn(async move {
        if let Ok((mut sock, _)) = listener.accept().await {
            let mut buf = [0u8; 2048];
            let _ = sock.read(&mut buf).await; // drain request headers
            let head = b"HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\ntransfer-encoding: chunked\r\n\r\n";
            let _ = sock.write_all(head).await;
            let _ = sock.write_all(b"b\r\ndata: one\n\n\r\n").await; // 11-byte chunk
            let _ = sock.flush().await;
            tokio::time::sleep(DELAY).await;
            let _ = sock.write_all(b"b\r\ndata: two\n\n\r\n").await;
            let _ = sock.write_all(b"0\r\n\r\n").await; // chunked terminator
            let _ = sock.flush().await;
        }
    });

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = format!("http://{up_addr}");
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(Config::default()),
            Ledger::disabled(),
            None,
        )
        .await;
    });
    await_listening(gw_addr).await;

    let client = reqwest::Client::builder().build().unwrap();
    let start = std::time::Instant::now();
    let mut res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .body(br#"{"model":"claude","messages":[]}"#.to_vec())
        .send()
        .await
        .expect("send through gateway");

    // First chunk must arrive well before the upstream sent the second one.
    let first = res
        .chunk()
        .await
        .expect("read first chunk")
        .expect("first chunk has bytes");
    let t_first = start.elapsed();
    assert!(
        first.starts_with(b"data: one"),
        "unexpected first chunk: {first:?}"
    );
    assert!(
        t_first < DELAY / 2,
        "first chunk took {t_first:?} (>= {:?}) — the gateway buffered instead of streaming",
        DELAY / 2
    );

    // The second event arrives only after the upstream's delay — proving the
    // stream stayed open and forwarded incrementally rather than all at once.
    let mut saw_two = false;
    while let Some(chunk) = res.chunk().await.expect("read chunk") {
        if chunk.windows(3).any(|w| w == b"two") {
            saw_two = true;
        }
    }
    assert!(saw_two, "second SSE event never arrived");
    assert!(
        start.elapsed() >= DELAY,
        "whole response arrived in {:?} (< {DELAY:?}) — not actually streamed",
        start.elapsed()
    );
}

/// End-to-end proof that `--audit`/`TRIMWIRE_AUDIT` (threaded as the gateway's
/// `audit_path` param) writes one metadata-only JSONL line per request: the
/// right shape/counts and headers, and — the load-bearing assertion — never the
/// message content itself.
#[tokio::test]
async fn wire_audit_records_metadata_only_never_content() {
    let upstream = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/v1/messages"))
        .respond_with(ResponseTemplate::new(200).set_body_bytes(b"ok".to_vec()))
        .mount(&upstream)
        .await;

    let dir = tempfile::tempdir().expect("tempdir");
    let audit_path = dir.path().join("audit.jsonl");
    let audit_str = audit_path.to_str().expect("utf8 path").to_owned();

    let (listener, gw_addr) = bind_listener().await;
    let upstream_uri = upstream.uri();
    tokio::spawn(async move {
        let _ = gateway::run_from_listener(
            listener,
            upstream_uri,
            Arc::new(Config::default()),
            Ledger::disabled(),
            Some(audit_str),
        )
        .await;
    });
    await_listening(gw_addr).await;

    // A canary that must never appear in the audit, plus one string-content and
    // one array-content tool_result so the shape counters have something to count.
    let secret = "LEAK_CANARY_DO_NOT_RECORD";
    let body = serde_json::to_vec(&json!({
        "model": "claude-opus-4-8",
        "messages": [
            {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": format!("port {secret}")}
            ]},
            {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t2", "content": [{"type": "text", "text": "arr"}]}
            ]},
        ]
    }))
    .expect("encode body");

    let client = reqwest::Client::builder().build().expect("client");
    let res = client
        .post(format!("http://{gw_addr}/v1/messages"))
        .header("content-type", "application/json")
        .header("x-claude-code-session-id", "sess-AUDIT")
        .header("anthropic-beta", "context-management-2025-06-27")
        .body(body)
        .send()
        .await
        .expect("send");
    assert_eq!(res.status().as_u16(), 200);

    // The audit write is synchronous (before the forward), but poll briefly to
    // stay robust to scheduling.
    let mut contents = String::new();
    for _ in 0..200 {
        if let Ok(s) = std::fs::read_to_string(&audit_path) {
            if !s.trim().is_empty() {
                contents = s;
                break;
            }
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    assert!(!contents.is_empty(), "audit file never got a line");
    assert!(
        !contents.contains(secret),
        "audit must be metadata-only — leaked message content: {contents}"
    );

    let line: Value =
        serde_json::from_str(contents.lines().next().expect("one line")).expect("parse audit line");
    assert_eq!(line["session_id"], json!("sess-AUDIT"));
    assert_eq!(line["model"], json!("claude-opus-4-8"));
    assert_eq!(
        line["anthropic_beta"],
        json!("context-management-2025-06-27")
    );
    assert_eq!(line["num_tool_result_blocks"], json!(2));
    assert_eq!(line["num_string_content"], json!(1));
    assert_eq!(line["num_array_content"], json!(1));
}
